# Generated by Django 5.2.11 on 2026-03-29 12:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id_log', models.BigAutoField(db_column='id_log', primary_key=True, serialize=False)),
                ('action', models.CharField(db_column='action', max_length=50)),
                ('entity_type', models.CharField(db_column='entity_type', max_length=50)),
                ('entity_id', models.IntegerField(db_column='entity_id')),
                ('old_data', models.JSONField(blank=True, db_column='old_data', null=True)),
                ('new_data', models.JSONField(blank=True, db_column='new_data', null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'db_table': 'audit_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id_commune', models.AutoField(db_column='id_commune', primary_key=True, serialize=False)),
                ('nom_commune', models.CharField(db_column='nom_commune', max_length=150)),
                ('code_commune', models.CharField(blank=True, db_column='code_commune', max_length=10, null=True)),
                ('type_commune', models.CharField(choices=[('Urbaine', 'Urbaine'), ('Rurale', 'Rurale')], db_column='type_commune', max_length=50)),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'db_table': 'commune',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(db_column='id_document', primary_key=True, serialize=False)),
                ('type_document', models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'Image'), ('OFFICIEL', 'Officiel'), ('AUTRE', 'Autre')], db_column='type_document', max_length=50)),
                ('file_name', models.CharField(db_column='file_name', max_length=255)),
                ('file_path', models.TextField(db_column='file_path')),
                ('file_size_mb', models.DecimalField(db_column='file_size_mb', decimal_places=2, max_digits=5)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='uploaded_at')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id_inspection', models.AutoField(db_column='id_inspection', primary_key=True, serialize=False)),
                ('date_inspection', models.DateField(db_column='date_inspection')),
                ('etat', models.CharField(choices=[('BON', 'Bon'), ('MOYEN', 'Moyen'), ('DEGRADE', 'Dégradé')], db_column='etat', max_length=50)),
                ('observations', models.TextField(blank=True, db_column='observations', null=True)),
                ('archived_at', models.DateTimeField(blank=True, db_column='archived_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'db_table': 'inspection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionModificationRequest',
            fields=[
                ('id_request', models.AutoField(db_column='id_request', primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_column='requested_at')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], db_column='status', default='PENDING', max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewed_at', null=True)),
                ('admin_note', models.TextField(blank=True, db_column='admin_note', null=True)),
                ('proposed_data', models.JSONField(db_column='proposed_data')),
            ],
            options={
                'verbose_name': "Demande de modification d'inspection",
                'verbose_name_plural': "Demandes de modification d'inspection",
                'db_table': 'inspection_modification_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id_intervention', models.AutoField(db_column='id_intervention', primary_key=True, serialize=False)),
                ('nom_projet', models.CharField(db_column='nom_projet', max_length=300)),
                ('type_intervention', models.CharField(choices=[('RESTAURATION', 'Restauration'), ('REHABILITATION', 'Réhabilitation'), ('AUTRE', 'Autre')], db_column='type_intervention', max_length=50)),
                ('date_debut', models.DateField(db_column='date_debut')),
                ('date_fin', models.DateField(blank=True, db_column='date_fin', null=True)),
                ('prestataire', models.CharField(blank=True, db_column='prestataire', max_length=300, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('SUSPENDUE', 'Suspendue'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], db_column='statut', default='PLANIFIEE', max_length=50)),
                ('date_validation', models.DateTimeField(blank=True, db_column='date_validation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'db_table': 'intervention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patrimoine',
            fields=[
                ('id_patrimoine', models.AutoField(db_column='id_patrimoine', primary_key=True, serialize=False)),
                ('nom_fr', models.CharField(db_column='nom_fr', max_length=300)),
                ('nom_ar', models.CharField(blank=True, db_column='nom_ar', max_length=300, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('type_patrimoine', models.CharField(choices=[('MONDIAL', 'Patrimoine Mondial'), ('NATUREL', 'Patrimoine Naturel'), ('HISTORIQUE', 'Monument Historique'), ('AUTRE', 'Autres Types')], db_column='type_patrimoine', max_length=50)),
                ('statut', models.CharField(choices=[('CLASSE', 'Classé'), ('INSCRIT', 'Inscrit'), ('EN_ETUDE', "En cours d'étude"), ('AUTRE', 'Autre')], db_column='statut', default='EN_ETUDE', max_length=50)),
                ('reference_administrative', models.CharField(blank=True, db_column='reference_administrative', max_length=100, null=True)),
                ('polygon_geom', django.contrib.gis.db.models.fields.MultiPolygonField(db_column='polygon_geom', srid=4326)),
                ('centroid_geom', django.contrib.gis.db.models.fields.PointField(blank=True, db_column='centroid_geom', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Patrimoine',
                'verbose_name_plural': 'Patrimoines',
                'db_table': 'patrimoine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id_province', models.AutoField(db_column='id_province', primary_key=True, serialize=False)),
                ('nom_province', models.CharField(db_column='nom_province', max_length=150)),
                ('code_province', models.CharField(blank=True, db_column='code_province', max_length=10, null=True)),
                ('type_province', models.CharField(choices=[('Province', 'Province'), ('Préfecture', 'Préfecture')], db_column='type_province', max_length=50)),
            ],
            options={
                'verbose_name': 'Province/Préfecture',
                'verbose_name_plural': 'Provinces/Préfectures',
                'db_table': 'province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(db_column='id_region', primary_key=True, serialize=False)),
                ('nom_region', models.CharField(db_column='nom_region', max_length=150, unique=True)),
                ('code_region', models.CharField(blank=True, db_column='code_region', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'db_table': 'region',
                'managed': False,
            },
        ),
    ]
